# Site settings
author: Katelyn Peterson
title: 
header-img: img/home-bg.png
email: katelynrpeterson16@gmail.com
copyright_name: Katelyn Peterson
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  pete3249

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
